### ISSUE TITLE
[BUG]: Tour yields two "unexpected error" notifications

### ISSUE THREAD

**Issue by c0rydoras** [adfinis/timed#144]
### Description

When doing the tour, two "unexpected error" notifications happen

### Steps to Reproduce

1. start dev setup
```bash
git clone https://github.com/adfinis/timed
cd timed
make start
make keycloak-import
make loaddata
```
2. head to https://timed.local and log in (user doesn't matter)
3. Press continue/next buttons on tour
4. receive "unexpected error"

### Expected Behavior

No "unexpected error"

### Attachments

(in chronological order)

![image](https://github.com/adfinis/timed/assets/110528300/a10921db-cf17-47d6-b469-0a8ab8b7ba82)
![image](https://github.com/adfinis/timed/assets/110528300/9b3da93a-0562-454c-b869-9412d1176d10)
![image](https://github.com/adfinis/timed/assets/110528300/18b16257-d7f0-4156-abf3-d696b1f4b683)
![image](https://github.com/adfinis/timed/assets/110528300/4f493a5c-085d-4b10-b73b-6e45ef4be0cf)
![image](https://github.com/adfinis/timed/assets/110528300/1d2906cb-4f75-4c0d-a089-76316d7c9519)

### Version

v4.0.1

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by hairmare** [comment]
i put this on urgent because it might impact onbaoding

**Comment by derrabauke** [comment]
@MitanOmar could you have a look at this?

**Comment by MitanOmar** [comment]
```
TransitionAborted: TransitionAborted
    at buildTransitionAborted (http://localhost:4200/assets/vendor.js:65994:17)
    at logAbort (http://localhost:4200/assets/vendor.js:66447:12)
    at PrivateRouter.transitionDidError (http://localhost:4200/assets/vendor.js:33470:44)
    at http://localhost:4200/assets/vendor.js:66231:35
    at invokeCallback (http://localhost:4200/assets/vendor.js:68343:17)
    at publish (http://localhost:4200/assets/vendor.js:68329:9)
    at publishRejection (http://localhost:4200/assets/vendor.js:68278:5)
    at http://localhost:4200/assets/vendor.js:63924:54
    at invoke (http://localhost:4200/assets/vendor.js:62526:16)
    at Queue.flush (http://localhost:4200/assets/vendor.js:62442:13)
```
