### ISSUE TITLE
[BUG]: TLS error in budgetcheck job

### ISSUE THREAD

**Issue by hairmare** [adfinis/timed#196]
### Description

Budgetcheck seems to use insecure URLS somewhere on test
```
Found 7 pods, using pod/test-timed-budgetcheck-28604340-ccpmm
Traceback (most recent call last):
  File "/usr/local/bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/timed/notifications/management/commands/budget_check.py", line 55, in handle
    issue = redmine.issue.get(project.redmine_project.issue_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redminelib/managers/base.py", line 99, in get
    response = self.redmine.engine.request('get', self.url, params=self.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redminelib/engines/base.py", line 84, in request
    return self.process_response(self.session.request(method, url, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redminelib/engines/base.py", line 153, in process_response
    raise exceptions.HTTPProtocolError
redminelib.exceptions.HTTPProtocolError: Protocol redirect detected, Redmine URL expects HTTPS, but code uses HTTP or vice versa
```

### Steps to Reproduce

1. Look at logs on test K8s

### Expected Behavior

No error

### Additional Context

I'm not sure if this wasn't already fixed in 4.1.0 :thinking: 

If not i'm pretty sure it's not a huge issue and can be fixed easily.

### Version

4.0.3

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by c0rydoras** [comment]
this issue was caused by a misconfiguration of the `DJANGO_REDMINE_URL`
